name = "golden-price"
main = "src/index.ts"
compatibility_date = "2026-07-29"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

routes = [
  { pattern = "api.gold.yuler.dev", custom_domain = true }
]

[[r2_buckets]]
binding = "GOLDEN_PRICE_DATA"
bucket_name = "golden-price-data"
preview_bucket_name = "golden-price-data-preview"

[triggers]
crons = ["*/5 * * * *"]

[[durable_objects.bindings]]
name = "COLLECTOR"
class_name = "PriceCollector"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["PriceCollector"]

[observability]
enabled = true
head_sampling_rate = 1
