name: Data Collect

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version-file: ".node-version"
          cache: pnpm

      - name: Install
        run: pnpm install

      - name: Collect
        run: pnpm cli:collect

      - name: Commit data
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "📊 Update data"
          file_pattern: "data/"
